# Generated by Django 3.0.8 on 2022-05-07 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('model', models.CharField(default='', max_length=120)),
                ('manufacturer', models.CharField(default='', max_length=120)),
                ('cost_in_credits', models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('length', models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_atmosphering_speed', models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('crew', models.CharField(default='', max_length=120)),
                ('passengers', models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cargo_capacity', models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hyperdrive_rating', models.CharField(default='', max_length=120)),
                ('MGLT', models.CharField(default='', max_length=120)),
                ('starship_class', models.CharField(default='', max_length=120)),
                ('created', models.CharField(default='', max_length=200)),
                ('edited', models.CharField(default='', max_length=200)),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
