# Generated by Django 3.0.8 on 2022-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starship',
            name='id_api',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
