# Generated by Django 3.0.8 on 2022-05-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starships', '0002_starship_id_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='id_api',
            field=models.IntegerField(unique=True),
        ),
    ]
